version: "3.9"

services:
  mysql_db:
    image: mysql:8.4
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: microservice-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"
    networks:
      - ms-network
      
  mongodb:
    image: mongo  # Fixed image name
    container_name: mongo_container
    restart: always
    environment:
       MONGO_INITDB_ROOT_USERNAME: admin
       MONGO_INITDB_ROOT_PASSWORD: admin
       MONGO_INITDB_DATABASE: order-service
    ports:
      - "27017:27017"
    command: ["mongod", "--auth"]
    networks:
      - ms-network  # Added network

  eureka-service:
    image: nikitamane/eurekaserver
    container_name: eureka-service
    restart: always
    ports:
      - "8722:8761"
    networks:
      - ms-network
      
  order-service:
    image: nikitamane/order-service
    container_name: order-service
    restart: always
    depends_on:
      - eureka-service
      - mongodb
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
      SPRING_DATA_MONGODB_URI: mongodb://admin:admin@mongo_container:27017/order-service?authSource=admin
    ports:
      - "1012:9092"
    networks:
      - ms-network

  restorantlisting:
    image: nikitamane/restorantlisting
    container_name: restorantlistings
    restart: always
    depends_on:
      - mysql_db
      - eureka-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/microservice-db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    ports:
      - "1013:9093"
    networks:
      - ms-network

  foodcatalogue:
    image: nikitamane/foodcatalogue
    container_name: foodcatalogue
    restart: always
    depends_on:
      - mysql_db
      - eureka-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/microservice-db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    ports:
      - "1011:9091"
    networks:
      - ms-network

  userinfo:
    image: nikitamane/userinfo
    container_name: userinfo
    restart: always
    depends_on:
      - mysql_db
      - eureka-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_db:3306/microservice-db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: root
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    ports:
      - "1014:9094"
    networks:
      - ms-network

networks:
  ms-network:
    driver: bridge
