server:
  port: 9091
  
  
spring:
  profiles:
    active: dev
    
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  
#spring:
# datasource:
#   url: jdbc:mysql://localhost:3306/udemy-db
#   
#   username: root
#   password: root
#   
# jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect  # Add Hibernate dialect
#        show_sql: true  # Optional: Show SQL queries in logs
#      
#eureka:
# instance:
#   prefer-ip-address: true
#   
# client:
#   serviceUrl:
#     defaultZone: http://localhost:8761/eureka
#     
#   fetch-registry: true
#   register-with-eureka: true